### ISSUE TITLE
Windows/DOS line endings in parameters cause jobs to fail under Slurm

### ISSUE THREAD

**Issue by dasmoth** [bartongroup/slivka#120]
In general, Slivka quotes command parameters when generating scripts to pass to the batch system.  So, for example, if I include a newline in a parameter, I might end up with a batch system script which looks like:

```
#!/usr/bin/env sh
touch started
python /path/to/example.py --rep 1,2 --delay 0 -- 'some
thing'
echo $? > finished
```

...which works as intended.

However, there's a special case if carriage returns are present.  Consider a nearly-identical example, but with a Windows line-ending (carriage return, line feed, ASCII 0x0d,0x0a) in the quoted parameter.  This still works fine as a shell script, but is unfortunately no longer a valid Slurm batch script.  `sbatch` exits with:

```
sbatch: error: Batch script contains DOS line breaks (\r\n)
sbatch: error: instead` of expected UNIX line breaks (\n)
```

(In combination with #119 this currently kills the Slivka scheduler).

I appreciate this is a fairly obscure edge case, but thought it was worth raising, since it means that there are inputs which I would expect to work with other runners, but to fail under SlurmRunner, which is a bit annoying.  And when dealing with user input, especially from web interfaces, Windows line endings are something that tend to show up when you're not expecting them.

For what it's worth, Slurm *will* accept:

```
#!/usr/bin/env bash
touch started
python /path/to/example.py -- rep 1,2 --delay 0 -- $'some\r\nthing'
echo $? > finished
```

_i.e._ bash's C-style escaping.  I don't know if this is a _good_ solution (in particular, I can see the merits of not depending on bash), but it is a possible answer.

**Comment by foreveremain** [comment]
in the general case I guess proper escaping should be done, but I shudder to think of the commandline tools that pass newlines via optargs !!  I'm fairly sure SGE and other schedulers will similarly balk unless proper bash syntax (like <<END : https://stackoverflow.com/questions/32126653/how-does-end-work-in-bash-to-create-a-multi-line-comment-block )

**Comment by warownia1** [comment]
I agree that proper escaping is the way to go, however it's a very shell
dependent solution

**Comment by dasmoth** [comment]
foreveremain: yes, completely agree, this is a very awkward corner that probably isn't going to happen intentionally.  However, it does creep in once you're dealing with (potentially copy-pasted) user input.

I'm not sure myself what would be the best solution.  Just forbidding this kind of input might not be totally unreasonable, but in that case I suggest it should be an error at job submission time, rather than accepting the job then failing in a -- runner-dependent -- fashion.

warownia1: in a sense, I don't think this is particularly shell-dependent as such -- rather, it's down to Slurm imposing some requirements that the actual shells do not.  On that basis, one possible solution would be to write the command line to the filesystem as a _separate_ shell script, and then just make the job script submitted to Slurm a shim which invokes the "actual" job script.

**Comment by warownia1** [comment]
What I meant by shell dependent is that different shells have slightly different ways to escape special characters. Does slurm respect shebang line and run the script with shell specified at the top of the file? If so, we can stick to sh escaping which should be quite easy to do.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
