### ISSUE TITLE
Add support for LSF workload manager

### ISSUE THREAD

**Issue by mukhyala** [bartongroup/slivka#128]
Similar to the current support for slurm, please extend to LSF as well.

**Comment by warownia1** [comment]
This issue will be resolved in the future version by the plugin system.
Currently, you can dynamically add LSF executor to slivka by extending the _Runner_ interface and placing it somewhere it can be imported by slivka e.g. in the project directory.
In the configuration file, enter the full python path to the class where you would enter the runner name.

Here is the runner template (copy it to the _plugins.py_ file):
```python
# plugins.py
from slivka.scheduler.runners import Runner, Job, Command, JobStatus

class LSFRunner(Runner):
  def submit(self, command: Command) -> Job:
    ...

  def check_status(self, job: Job) -> JobStatus
    ...

  def cancel(self, job: Job):
    ...
```
and the runner configuration which goes to the _service.yaml_ file
```yaml
execution:
  runners:
    default:
      type: plugins.LSFRunner
```
