### ISSUE TITLE
Add support for Slurm workload manager

### ISSUE THREAD

**Issue by warownia1** [bartongroup/slivka#98]
Add an implementation of Runner which would run jobs with Slurm

**Comment by foreveremain** [comment]
a development branch has been pushed https://github.com/bartongroup/slivka/commit/da2d1ac95ffedd3c313e72372c5664ae1862e7c1

Install direct via pip and configure via 'SlurmRunner'

**Comment by foreveremain** [comment]
bumping this @warownia1 - the SlurmRunner fork needs to be merged, and the README updated to reflect Slurm capability :)

**Comment by warownia1** [comment]
I merged it today and wanted to run tests before committing and pushing the changes. I spent the rest of the day trying to set up Slurm on a VM, but I couldn't make it work. Do you have an idea how can I test Slurm interoperability without actually having it actually installed? It would be best to test it with a real Slurm, but being able to run unit tests without setting up the cluster is also important.

**Comment by foreveremain** [comment]
Did you try this ?

https://github.com/hokiegeek2/slurm-cloud-integration
